name: Deploy and test on Vercel

inputs:
  RATELIMIT_VERSION:
    required: true
  REDIS_VERSION: 
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2
      with:
        version: 6

    - name: Install example
      run: pnpm add @upstash/ratelimit@${{inputs.RATELIMIT_VERSION}}  @upstash/redis@${{inputs.REDIS_VERSION}} 
      working-directory: ./examples/nextjs

    - name: Deploy
      run: npx vercel
      working-directory: ./examples/nextjs
