name: Deploy and test on Vercel

inputs:
  ratelimit_version:
    required: true
  redis_version: 
    required: true

outputs:
  url:
    description: "Vercel deployment url"
    value: ${{ steps.deployment.outputs.url}}


runs:
  using: "composite"

  steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2
      with:
        version: 6

    - name: Install example
      shell: bash
      run: |
        pnpm add @upstash/ratelimit@${{inputs.RATELIMIT_VERSION}}  @upstash/redis@${{inputs.REDIS_VERSION}}
        pnpm add -g vercel
      working-directory: ./examples/nextjs

    - name: Deploy      
      shell: bash
      id: deployment
      working-directory: ./examples/nextjs
      
      run: |
        url=$(vercel --token=${{ secrets.VERCEL_TOKEN }})
        echo "::set-output name=url::${url}"

