packages:
  - "packages/*"

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@upstash/redis"
blockExoticSubdeps: true

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true

# trustPolicy: no-downgrade
