version: '3'


tasks:

  build:
    deps:
      - fmt
    cmds:
      - bun run build
  
  test:
    deps:
      - build
    cmds:
      - deno test -A ./pkg/**/*.ts

  test-ci:
    deps:
      - build
    cmds:
      -  act pull_request --container-architecture linux/amd64 --secret-file .env