version: '3'


tasks:
  fmt: 
    cmds:
      - deno fmt 
      - deno lint

 
  build:
    deps:
      - fmt
    cmds:
      - deno run -A ./cmd/build.ts
  
  test:
    deps:
      - build
    cmds:
      - deno test -A ./pkg/**/*.ts

  test-ci:
    deps:
      - build
    cmds:
      -  act pull_request --container-architecture linux/amd64 --secret-file .env