name = "cloudflare-workers-with-typescript"
main = "src/index.ts"
compatibility_date = "2022-05-31"


# Set variables here or on cloudflare
# [vars]
# UPSTASH_REDIS_REST_URL = "REPLACE_THIS"
# UPSTASH_REDIS_REST_TOKEN = "REPLACE_THIS"
