name: npm Publish

on:
  workflow_call:
    inputs:
      prerelease:
        type: boolean
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Set package version
        run: |
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' packages/redis/package.json) > packages/redis/package.json
          echo "export const VERSION='${{ env.VERSION }}'" > packages/redis/version.ts

      - name: Build
        run: pnpm -r build

      - name: Publish
        if: ${{ !inputs.prerelease }}
        working-directory: ./packages/redis/dist
        run: |
          npm pkg delete scripts.prepare
          npm publish --provenance --access public
        env:
          NPM_CONFIG_PROVENANCE: "true"

      - name: Publish release candidate
        if: ${{ inputs.prerelease }}
        working-directory: ./packages/redis/dist
        run: |
          npm pkg delete scripts.prepare
          npm publish --provenance --access public --tag=canary
        env:
          NPM_CONFIG_PROVENANCE: "true"
