name: Create local redis server

on:
  workflow_call:
    inputs:
      REST_URL:
        required: true
        type: string
    secrets:
      REST_TOKEN:
        required: true
      REPO_TOKEN:
        required: true

jobs:
  start-local-redis:
    name: Create a local redis instance
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Check out Redis Server
        uses: actions/checkout@v2
        with:
          repository: upstash/redis-server
          token: ${{ secrets.REPO_TOKEN }}
          path: redis-server

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: "true"
          go-version: "^1.17"

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-redis-server-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-redis-server

      - name: Create Server Config
        run: |
          echo "$REDIS_SERVER_CONFIG" >> config.json
        shell: bash
        env:
          REDIS_SERVER_CONFIG: ${{secrets.REDIS_SERVER_CONFIG}}

      - name: Start Redis Server
        run: |
          make
          ./upstash-redis -log-level error -config $GITHUB_WORKSPACE/config.json &
        working-directory: ./redis-server/cmd

      - name: Ping redis server
        run: |
          curl $UPSTASH_REDIS_REST_URL/info -H "Authorization: Bearer $UPSTASH_REDIS_REST_TOKEN"
        env:
          UPSTASH_REDIS_REST_URL: ${{ inputs.REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.REST_TOKEN }}
